<a href="https://colab.research.google.com/github/shashithenuwara/IOT/blob/main/MLmodel.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install firebase-admin pandas

Requirement already satisfied: firebase-admin in /usr/local/lib/python3.12/dist-packages (6.9.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: cachecontrol>=0.12.14 in /usr/local/lib/python3.12/dist-packages (from firebase-admin) (0.14.4)
Requirement already satisfied: google-api-python-client>=1.7.8 in /usr/local/lib/python3.12/dist-packages (from firebase-admin) (2.194.0)
Requirement already satisfied: google-cloud-storage>=1.37.1 in /usr/local/lib/python3.12/dist-packages (from firebase-admin) (3.10.1)
Requirement already satisfied: pyjwt>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from pyjwt[crypto]>=2.5.0->firebase-admin) (2.12.1)
Requirement already satisfied: httpx==0.28.1 in /usr/local/lib/python3.12/dist-packages (from httpx[http2]==0.28.1->firebase-admin) (0.28.1)
Requirement already satisfied: google-api-core<3.0.0dev,>=1.22.1 in /usr/local/lib/python3.12/dist-packages (from google-api-core[grpc]<3.0.0dev,>=1.22.1; platform_python_implementation != "PyPy"->firebase-admin) (2.30.3)
Requirement already satisfied: google-cloud-firestore>=2.19.0 in /usr/local/lib/python3.12/dist-packages (from firebase-admin) (2.26.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx==0.28.1->httpx[http2]==0.28.1->firebase-admin) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx==0.28.1->httpx[http2]==0.28.1->firebase-admin) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx==0.28.1->httpx[http2]==0.28.1->firebase-admin) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx==0.28.1->httpx[http2]==0.28.1->firebase-admin) (3.11)
Requirement already satisfied: h2<5,>=3 in /usr/local/lib/python3.12/dist-packages (from httpx[http2]==0.28.1->firebase-admin) (4.3.0)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx==0.28.1->httpx[http2]==0.28.1->firebase-admin) (0.16.0)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: requests>=2.16.0 in /usr/local/lib/python3.12/dist-packages (from cachecontrol>=0.12.14->firebase-admin) (2.32.4)
Requirement already satisfied: msgpack<2.0.0,>=0.5.2 in /usr/local/lib/python3.12/dist-packages (from cachecontrol>=0.12.14->firebase-admin) (1.1.2)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.63.2 in /usr/local/lib/python3.12/dist-packages (from google-api-core<3.0.0dev,>=1.22.1->google-api-core[grpc]<3.0.0dev,>=1.22.1; platform_python_implementation != "PyPy"->firebase-admin) (1.74.0)
Requirement already satisfied: protobuf<8.0.0,>=4.25.8 in /usr/local/lib/python3.12/dist-packages (from google-api-core<3.0.0dev,>=1.22.1->google-api-core[grpc]<3.0.0dev,>=1.22.1; platform_python_implementation != "PyPy"->firebase-admin) (5.29.6)
Requirement already satisfied: proto-plus<2.0.0,>=1.22.3 in /usr/local/lib/python3.12/dist-packages (from google-api-core<3.0.0dev,>=1.22.1->google-api-core[grpc]<3.0.0dev,>=1.22.1; platform_python_implementation != "PyPy"->firebase-admin) (1.27.2)
Requirement already satisfied: google-auth<3.0.0,>=2.14.1 in /usr/local/lib/python3.12/dist-packages (from google-api-core<3.0.0dev,>=1.22.1->google-api-core[grpc]<3.0.0dev,>=1.22.1; platform_python_implementation != "PyPy"->firebase-admin) (2.47.0)
Requirement already satisfied: grpcio<2.0.0,>=1.33.2 in /usr/local/lib/python3.12/dist-packages (from google-api-core[grpc]<3.0.0dev,>=1.22.1; platform_python_implementation != "PyPy"->firebase-admin) (1.80.0)
Requirement already satisfied: grpcio-status<2.0.0,>=1.33.2 in /usr/local/lib/python3.12/dist-packages (from google-api-core[grpc]<3.0.0dev,>=1.22.1; platform_python_implementation != "PyPy"->firebase-admin) (1.71.2)
Requirement already satisfied: httplib2<1.0.0,>=0.19.0 in /usr/local/lib/python3.12/dist-packages (from google-api-python-client>=1.7.8->firebase-admin) (0.31.2)
Requirement already satisfied: google-auth-httplib2<1.0.0,>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from google-api-python-client>=1.7.8->firebase-admin) (0.3.1)
Requirement already satisfied: uritemplate<5,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from google-api-python-client>=1.7.8->firebase-admin) (4.2.0)
Requirement already satisfied: google-cloud-core<3.0.0,>=1.4.1 in /usr/local/lib/python3.12/dist-packages (from google-cloud-firestore>=2.19.0->firebase-admin) (2.5.1)
Requirement already satisfied: google-resumable-media<3.0.0,>=2.7.2 in /usr/local/lib/python3.12/dist-packages (from google-cloud-storage>=1.37.1->firebase-admin) (2.8.2)
Requirement already satisfied: google-crc32c<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from google-cloud-storage>=1.37.1->firebase-admin) (1.8.0)
Requirement already satisfied: cryptography>=3.4.0 in /usr/local/lib/python3.12/dist-packages (from pyjwt[crypto]>=2.5.0->firebase-admin) (43.0.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.12/dist-packages (from cryptography>=3.4.0->pyjwt[crypto]>=2.5.0->firebase-admin) (2.0.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from google-auth<3.0.0,>=2.14.1->google-api-core<3.0.0dev,>=1.22.1->google-api-core[grpc]<3.0.0dev,>=1.22.1; platform_python_implementation != "PyPy"->firebase-admin) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from google-auth<3.0.0,>=2.14.1->google-api-core<3.0.0dev,>=1.22.1->google-api-core[grpc]<3.0.0dev,>=1.22.1; platform_python_implementation != "PyPy"->firebase-admin) (4.9.1)
Requirement already satisfied: typing-extensions~=4.12 in /usr/local/lib/python3.12/dist-packages (from grpcio<2.0.0,>=1.33.2->google-api-core[grpc]<3.0.0dev,>=1.22.1; platform_python_implementation != "PyPy"->firebase-admin) (4.15.0)
Requirement already satisfied: hyperframe<7,>=6.1 in /usr/local/lib/python3.12/dist-packages (from h2<5,>=3->httpx[http2]==0.28.1->firebase-admin) (6.1.0)
Requirement already satisfied: hpack<5,>=4.1 in /usr/local/lib/python3.12/dist-packages (from h2<5,>=3->httpx[http2]==0.28.1->firebase-admin) (4.1.0)
Requirement already satisfied: pyparsing<4,>=3.1 in /usr/local/lib/python3.12/dist-packages (from httplib2<1.0.0,>=0.19.0->google-api-python-client>=1.7.8->firebase-admin) (3.3.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.16.0->cachecontrol>=0.12.14->firebase-admin) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.16.0->cachecontrol>=0.12.14->firebase-admin) (2.5.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.12->cryptography>=3.4.0->pyjwt[crypto]>=2.5.0->firebase-admin) (3.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.12/dist-packages (from pyasn1-modules>=0.2.1->google-auth<3.0.0,>=2.14.1->google-api-core<3.0.0dev,>=1.22.1->google-api-core[grpc]<3.0.0dev,>=1.22.1; platform_python_implementation != "PyPy"->firebase-admin) (0.6.3)

In [2]:
from google.colab import files
uploaded = files.upload()

Saving iotdba-firebase-adminsdk-fbsvc-9b342554a8.json to iotdba-firebase-adminsdk-fbsvc-9b342554a8.json

In [24]:
import firebase_admin
from firebase_admin import credentials, db
import pandas as pd

# Path to your downloaded service account file
SERVICE_ACCOUNT_FILE = "iotdba-firebase-adminsdk-fbsvc-9b342554a8.json"

# Your Firebase Realtime Database URL
DATABASE_URL = "https://iotdba-default-rtdb.firebaseio.com/"

# Initialize only once
if not firebase_admin._apps:
    cred = credentials.Certificate(SERVICE_ACCOUNT_FILE)
    firebase_admin.initialize_app(cred, {
        "databaseURL": DATABASE_URL
    })

# Example: read from a node called 'sensor_data'
ref = db.reference("/logs")
data = ref.get()

print(type(data))
print(data)

<class 'dict'>

In [25]:
df = pd.DataFrame.from_dict(data, orient="index")
df.head(40)
df.shape

(7046, 8)

In [26]:
#Ensure columns are numeric
df["temperature"] = pd.to_numeric(df["temperature"], errors="coerce")
df["humidity"] = pd.to_numeric(df["humidity"], errors="coerce")
df["light"] = pd.to_numeric(df["light"], errors="coerce")
df["air_quality_ppm"] = pd.to_numeric(df["air_quality_ppm"], errors="coerce")

In [28]:
#Drop Null vals
df = df.dropna()
df.shape

(7046, 8)

In [33]:
#Naming the first column
df = pd.DataFrame.from_dict(data, orient="index").reset_index().rename(columns={"index": "record_id"})

In [34]:
#Feature Engineering - Add new column
df["temp_critical"] = (df["temperature"] >= 30).astype(int)
df["hum_critical"] = (df["humidity"] >= 65).astype(int)
df["light_critical"] = (df["light"] >= 300).astype(int)
df["air_critical"] = (df["air_quality_ppm"] >= 1000).astype(int)
def get_critical_feature(row):
    critical = []

    if row["temp_critical"] == 1:
        critical.append("temperature")
    if row["hum_critical"] == 1:
        critical.append("humidity")
    if row["light_critical"] == 1:
        critical.append("light")
    if row["air_critical"] == 1:
        critical.append("air_quality_ppm")

    return ",".join(critical) if critical else "normal"

df["critical_feature"] = df.apply(get_critical_feature, axis=1)
df.head(40)

,record_id,air_quality_ppm,date,humidity,light,status,temperature,time,timestamp,temp_critical,hum_critical,light_critical,air_critical,critical_feature
0,-Oqk0awQcHb_miuPnopu,176.5871,2026-04-21,75.6,0.833333,CRITICAL,29.4375,18:01:43,2026-04-21 18:01:43,0,1,0,0,humidity
1,-Oqk0eiMekEmU_mr2i2B,174.7966,2026-04-21,75.2,0.833333,CRITICAL,29.4375,18:01:57,2026-04-21 18:01:57,0,1,0,0,humidity
2,-Oqk1-ebRgI2Jcc2er0k,170.3727,2026-04-21,74.5,0.833333,CRITICAL,29.4375,18:03:28,2026-04-21 18:03:28,0,1,0,0,humidity
3,-Oqk132q5e3Wgsl0-306,172.1333,2026-04-21,74.4,0.833333,CRITICAL,29.3750,18:03:42,2026-04-21 18:03:42,0,1,0,0,humidity
4,-Oqk16TBEYzhXoFLYdK2,159.2145,2026-04-21,74.4,133.333300,CRITICAL,29.4375,18:03:56,2026-04-21 18:03:56,0,1,0,0,humidity
5,-Oqk19xT3H0_G3sNmugT,173.0182,2026-04-21,74.6,1499.167000,CRITICAL,29.4375,18:04:10,2026-04-21 18:04:10,0,1,1,0,"humidity,light"
6,-Oqk1DPIsyV0A-4pYogn,173.9059,2026-04-21,74.5,54.166660,CRITICAL,29.4375,18:04:24,2026-04-21 18:04:24,0,1,0,0,humidity
7,-Oqk1Gp6Cj-2_zZJse1L,168.6238,2026-04-21,74.5,37.500000,CRITICAL,30.3125,18:04:39,2026-04-21 18:04:39,1,1,0,0,"temperature,humidity"
8,-Oqk1KGW0aslWYBH_88k,173.0182,2026-04-21,74.5,37.500000,CRITICAL,32.9375,18:04:53,2026-04-21 18:04:53,1,1,0,0,"temperature,humidity"
9,-Oqk1NeaUaPz_f9OSjNd,173.0182,2026-04-21,74.5,36.666660,CRITICAL,33.8125,18:05:07,2026-04-21 18:05:07,1,1,0,0,"temperature,humidity"
10,-Oqk1RCsp7OVE5a5PCR7,173.0182,2026-04-21,74.5,36.666660,CRITICAL,33.5625,18:05:21,2026-04-21 18:05:21,1,1,0,0,"temperature,humidity"
11,-Oqk1ju3NNkpFCh4zH73,166.8867,2026-04-21,74.5,36.666660,CRITICAL,32.1875,18:06:40,2026-04-21 18:06:40,1,1,0,0,"temperature,humidity"
12,-Oqk1nJ2BeeYEsl1wRAf,171.2516,2026-04-21,74.6,36.666660,CRITICAL,32.0000,18:06:56,2026-04-21 18:06:56,1,1,0,0,"temperature,humidity"
13,-Oqk1qmV9laPuE0GjJpH,165.1614,2026-04-21,74.7,36.666660,CRITICAL,31.8125,18:07:10,2026-04-21 18:07:10,1,1,0,0,"temperature,humidity"
14,-Oqk296Zd-a7_OEfL-Ga,167.7538,2026-04-21,74.9,36.666660,CRITICAL,31.5000,18:08:29,2026-04-21 18:08:29,1,1,0,0,"temperature,humidity"
15,-Oqk2Cb1mGjE_TZFngqf,171.2516,2026-04-21,74.9,36.666660,CRITICAL,31.4375,18:08:43,2026-04-21 18:08:43,1,1,0,0,"temperature,humidity"
16,-Oqk2G9SnQtHKSFoS9pg,171.2516,2026-04-21,74.7,36.666660,CRITICAL,31.4375,18:08:58,2026-04-21 18:08:58,1,1,0,0,"temperature,humidity"
17,-Oqk2Jka_n009XL1q56g,173.0182,2026-04-21,74.7,36.666660,CRITICAL,31.4375,18:09:12,2026-04-21 18:09:12,1,1,0,0,"temperature,humidity"
18,-Oqk2NIq7HwhISp-eKRf,173.0182,2026-04-21,75.0,36.666660,CRITICAL,31.3750,18:09:27,2026-04-21 18:09:27,1,1,0,0,"temperature,humidity"
19,-Oqk2QrqNx0XvJcAabkA,165.1614,2026-04-21,74.8,36.666660,CRITICAL,31.3125,18:09:42,2026-04-21 18:09:42,1,1,0,0,"temperature,humidity"
20,-Oqk2ULxGqvOvwcVkfq5,173.0182,2026-04-21,75.0,36.666660,CRITICAL,31.3125,18:09:56,2026-04-21 18:09:56,1,1,0,0,"temperature,humidity"
21,-Oqk2XrxCS2HCq3uRsIc,169.4968,2026-04-21,74.9,36.666660,CRITICAL,31.2500,18:10:10,2026-04-21 18:10:10,1,1,0,0,"temperature,humidity"
22,-Oqk2aYt24aFUEqw0wFo,173.9059,2026-04-21,74.9,1.666667,CRITICAL,31.3125,18:10:25,2026-04-21 18:10:25,1,1,0,0,"temperature,humidity"
23,-Oqk2eCLlvkBEfMOnF8A,169.4968,2026-04-21,74.8,36.666660,CRITICAL,31.3125,18:10:40,2026-04-21 18:10:40,1,1,0,0,"temperature,humidity"
24,-Oqk2hYsy8MEPXgdMF_5,167.7538,2026-04-21,74.9,36.666660,CRITICAL,31.3125,18:10:54,2026-04-21 18:10:54,1,1,0,0,"temperature,humidity"
25,-Oqk2l6HITwZ8r-7C-X6,166.0226,2026-04-21,74.9,36.666660,CRITICAL,31.3125,18:11:08,2026-04-21 18:11:08,1,1,0,0,"temperature,humidity"
26,-Oqk2ocCxOUY1nCVB3XR,175.6903,2026-04-21,74.8,36.666660,CRITICAL,31.3125,18:11:23,2026-04-21 18:11:23,1,1,0,0,"temperature,humidity"
27,-Oqk2s3JY0aNwUdDUpNF,163.4477,2026-04-21,74.8,36.666660,CRITICAL,31.3125,18:11:37,2026-04-21 18:11:37,1,1,0,0,"temperature,humidity"
28,-Oqk2vSQnXFLbhFOQ8hJ,177.4867,2026-04-21,74.7,36.666660,CRITICAL,31.3125,18:11:51,2026-04-21 18:11:51,1,1,0,0,"temperature,humidity"
29,-Oqk2yvIdaoVFSLgPZvD,176.5871,2026-04-21,74.8,36.666660,CRITICAL,31.3125,18:12:05,2026-04-21 18:12:05,1,1,0,0,"temperature,humidity"
30,-Oqk31TXU8qye2p07leb,167.7538,2026-04-21,74.8,36.666660,CRITICAL,31.3125,18:12:20,2026-04-21 18:12:20,1,1,0,0,"temperature,humidity"
31,-Oqk356M0ccBdWKwNTSZ,169.4968,2026-04-21,74.6,36.666660,CRITICAL,31.3125,18:12:34,2026-04-21 18:12:34,1,1,0,0,"temperature,humidity"
32,-Oqk38b4YyBJ8ozUGHyI,173.9059,2026-04-21,74.7,36.666660,CRITICAL,31.3125,18:12:49,2026-04-21 18:12:49,1,1,0,0,"temperature,humidity"
33,-Oqk3C3Qj2lqjhI1h_2X,171.2516,2026-04-21,74.8,36.666660,CRITICAL,31.2500,18:13:03,2026-04-21 18:13:03,1,1,0,0,"temperature,humidity"
34,-Oqk3FehP1fD1TAGCO2D,173.9059,2026-04-21,74.8,35.833330,CRITICAL,31.3125,18:13:18,2026-04-21 18:13:18,1,1,0,0,"temperature,humidity"
35,-Oqk3JPF4dg4A8d9jjZn,166.0226,2026-04-21,74.8,35.833330,CRITICAL,31.2500,18:13:33,2026-04-21 18:13:33,1,1,0,0,"temperature,humidity"
36,-Oqk3MhIXY3NqY99gG_H,169.4968,2026-04-21,75.2,35.833330,CRITICAL,31.2500,18:13:47,2026-04-21 18:13:47,1,1,0,0,"temperature,humidity"
37,-Oqk3Q02DVNznmHFveFs,157.5416,2026-04-21,75.4,36.666660,CRITICAL,31.2500,18:14:00,2026-04-21 18:14:00,1,1,0,0,"temperature,humidity"
38,-Oqk3TWK7YJDaVHIs6f1,170.3727,2026-04-21,75.4,36.666660,CRITICAL,31.2500,18:14:15,2026-04-21 18:14:15,1,1,0,0,"temperature,humidity"
39,-Oqk3X2p477E9Byx_aFl,173.9059,2026-04-21,75.2,36.666660,CRITICAL,31.2500,18:14:29,2026-04-21 18:14:29,1,1,0,0,"temperature,humidity"

,record_id,air_quality_ppm,date,humidity,light,status,temperature,time,timestamp
0,-Oqk0awQcHb_miuPnopu,176.5871,2026-04-21,75.6,0.833333,CRITICAL,29.4375,18:01:43,2026-04-21 18:01:43
1,-Oqk0eiMekEmU_mr2i2B,174.7966,2026-04-21,75.2,0.833333,CRITICAL,29.4375,18:01:57,2026-04-21 18:01:57
2,-Oqk1-ebRgI2Jcc2er0k,170.3727,2026-04-21,74.5,0.833333,CRITICAL,29.4375,18:03:28,2026-04-21 18:03:28
3,-Oqk132q5e3Wgsl0-306,172.1333,2026-04-21,74.4,0.833333,CRITICAL,29.3750,18:03:42,2026-04-21 18:03:42
4,-Oqk16TBEYzhXoFLYdK2,159.2145,2026-04-21,74.4,133.333300,CRITICAL,29.4375,18:03:56,2026-04-21 18:03:56
5,-Oqk19xT3H0_G3sNmugT,173.0182,2026-04-21,74.6,1499.167000,CRITICAL,29.4375,18:04:10,2026-04-21 18:04:10
6,-Oqk1DPIsyV0A-4pYogn,173.9059,2026-04-21,74.5,54.166660,CRITICAL,29.4375,18:04:24,2026-04-21 18:04:24
7,-Oqk1Gp6Cj-2_zZJse1L,168.6238,2026-04-21,74.5,37.500000,CRITICAL,30.3125,18:04:39,2026-04-21 18:04:39
8,-Oqk1KGW0aslWYBH_88k,173.0182,2026-04-21,74.5,37.500000,CRITICAL,32.9375,18:04:53,2026-04-21 18:04:53
9,-Oqk1NeaUaPz_f9OSjNd,173.0182,2026-04-21,74.5,36.666660,CRITICAL,33.8125,18:05:07,2026-04-21 18:05:07
10,-Oqk1RCsp7OVE5a5PCR7,173.0182,2026-04-21,74.5,36.666660,CRITICAL,33.5625,18:05:21,2026-04-21 18:05:21
11,-Oqk1ju3NNkpFCh4zH73,166.8867,2026-04-21,74.5,36.666660,CRITICAL,32.1875,18:06:40,2026-04-21 18:06:40
12,-Oqk1nJ2BeeYEsl1wRAf,171.2516,2026-04-21,74.6,36.666660,CRITICAL,32.0000,18:06:56,2026-04-21 18:06:56
13,-Oqk1qmV9laPuE0GjJpH,165.1614,2026-04-21,74.7,36.666660,CRITICAL,31.8125,18:07:10,2026-04-21 18:07:10
14,-Oqk296Zd-a7_OEfL-Ga,167.7538,2026-04-21,74.9,36.666660,CRITICAL,31.5000,18:08:29,2026-04-21 18:08:29
15,-Oqk2Cb1mGjE_TZFngqf,171.2516,2026-04-21,74.9,36.666660,CRITICAL,31.4375,18:08:43,2026-04-21 18:08:43
16,-Oqk2G9SnQtHKSFoS9pg,171.2516,2026-04-21,74.7,36.666660,CRITICAL,31.4375,18:08:58,2026-04-21 18:08:58
17,-Oqk2Jka_n009XL1q56g,173.0182,2026-04-21,74.7,36.666660,CRITICAL,31.4375,18:09:12,2026-04-21 18:09:12
18,-Oqk2NIq7HwhISp-eKRf,173.0182,2026-04-21,75.0,36.666660,CRITICAL,31.3750,18:09:27,2026-04-21 18:09:27
19,-Oqk2QrqNx0XvJcAabkA,165.1614,2026-04-21,74.8,36.666660,CRITICAL,31.3125,18:09:42,2026-04-21 18:09:42
20,-Oqk2ULxGqvOvwcVkfq5,173.0182,2026-04-21,75.0,36.666660,CRITICAL,31.3125,18:09:56,2026-04-21 18:09:56
21,-Oqk2XrxCS2HCq3uRsIc,169.4968,2026-04-21,74.9,36.666660,CRITICAL,31.2500,18:10:10,2026-04-21 18:10:10
22,-Oqk2aYt24aFUEqw0wFo,173.9059,2026-04-21,74.9,1.666667,CRITICAL,31.3125,18:10:25,2026-04-21 18:10:25
23,-Oqk2eCLlvkBEfMOnF8A,169.4968,2026-04-21,74.8,36.666660,CRITICAL,31.3125,18:10:40,2026-04-21 18:10:40
24,-Oqk2hYsy8MEPXgdMF_5,167.7538,2026-04-21,74.9,36.666660,CRITICAL,31.3125,18:10:54,2026-04-21 18:10:54
25,-Oqk2l6HITwZ8r-7C-X6,166.0226,2026-04-21,74.9,36.666660,CRITICAL,31.3125,18:11:08,2026-04-21 18:11:08
26,-Oqk2ocCxOUY1nCVB3XR,175.6903,2026-04-21,74.8,36.666660,CRITICAL,31.3125,18:11:23,2026-04-21 18:11:23
27,-Oqk2s3JY0aNwUdDUpNF,163.4477,2026-04-21,74.8,36.666660,CRITICAL,31.3125,18:11:37,2026-04-21 18:11:37
28,-Oqk2vSQnXFLbhFOQ8hJ,177.4867,2026-04-21,74.7,36.666660,CRITICAL,31.3125,18:11:51,2026-04-21 18:11:51
29,-Oqk2yvIdaoVFSLgPZvD,176.5871,2026-04-21,74.8,36.666660,CRITICAL,31.3125,18:12:05,2026-04-21 18:12:05
30,-Oqk31TXU8qye2p07leb,167.7538,2026-04-21,74.8,36.666660,CRITICAL,31.3125,18:12:20,2026-04-21 18:12:20
31,-Oqk356M0ccBdWKwNTSZ,169.4968,2026-04-21,74.6,36.666660,CRITICAL,31.3125,18:12:34,2026-04-21 18:12:34
32,-Oqk38b4YyBJ8ozUGHyI,173.9059,2026-04-21,74.7,36.666660,CRITICAL,31.3125,18:12:49,2026-04-21 18:12:49
33,-Oqk3C3Qj2lqjhI1h_2X,171.2516,2026-04-21,74.8,36.666660,CRITICAL,31.2500,18:13:03,2026-04-21 18:13:03
34,-Oqk3FehP1fD1TAGCO2D,173.9059,2026-04-21,74.8,35.833330,CRITICAL,31.3125,18:13:18,2026-04-21 18:13:18
35,-Oqk3JPF4dg4A8d9jjZn,166.0226,2026-04-21,74.8,35.833330,CRITICAL,31.2500,18:13:33,2026-04-21 18:13:33
36,-Oqk3MhIXY3NqY99gG_H,169.4968,2026-04-21,75.2,35.833330,CRITICAL,31.2500,18:13:47,2026-04-21 18:13:47
37,-Oqk3Q02DVNznmHFveFs,157.5416,2026-04-21,75.4,36.666660,CRITICAL,31.2500,18:14:00,2026-04-21 18:14:00
38,-Oqk3TWK7YJDaVHIs6f1,170.3727,2026-04-21,75.4,36.666660,CRITICAL,31.2500,18:14:15,2026-04-21 18:14:15
39,-Oqk3X2p477E9Byx_aFl,173.9059,2026-04-21,75.2,36.666660,CRITICAL,31.2500,18:14:29,2026-04-21 18:14:29

In [37]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df["critical_feature_encoded"] = le.fit_transform(df["critical_feature"])
df.head(40)

,record_id,air_quality_ppm,date,humidity,light,status,temperature,time,timestamp,temp_critical,hum_critical,light_critical,air_critical,critical_feature,critical_feature_encoded
0,-Oqk0awQcHb_miuPnopu,176.5871,2026-04-21,75.6,0.833333,CRITICAL,29.4375,18:01:43,2026-04-21 18:01:43,0,1,0,0,humidity,0
1,-Oqk0eiMekEmU_mr2i2B,174.7966,2026-04-21,75.2,0.833333,CRITICAL,29.4375,18:01:57,2026-04-21 18:01:57,0,1,0,0,humidity,0
2,-Oqk1-ebRgI2Jcc2er0k,170.3727,2026-04-21,74.5,0.833333,CRITICAL,29.4375,18:03:28,2026-04-21 18:03:28,0,1,0,0,humidity,0
3,-Oqk132q5e3Wgsl0-306,172.1333,2026-04-21,74.4,0.833333,CRITICAL,29.3750,18:03:42,2026-04-21 18:03:42,0,1,0,0,humidity,0
4,-Oqk16TBEYzhXoFLYdK2,159.2145,2026-04-21,74.4,133.333300,CRITICAL,29.4375,18:03:56,2026-04-21 18:03:56,0,1,0,0,humidity,0
5,-Oqk19xT3H0_G3sNmugT,173.0182,2026-04-21,74.6,1499.167000,CRITICAL,29.4375,18:04:10,2026-04-21 18:04:10,0,1,1,0,"humidity,light",1
6,-Oqk1DPIsyV0A-4pYogn,173.9059,2026-04-21,74.5,54.166660,CRITICAL,29.4375,18:04:24,2026-04-21 18:04:24,0,1,0,0,humidity,0
7,-Oqk1Gp6Cj-2_zZJse1L,168.6238,2026-04-21,74.5,37.500000,CRITICAL,30.3125,18:04:39,2026-04-21 18:04:39,1,1,0,0,"temperature,humidity",4
8,-Oqk1KGW0aslWYBH_88k,173.0182,2026-04-21,74.5,37.500000,CRITICAL,32.9375,18:04:53,2026-04-21 18:04:53,1,1,0,0,"temperature,humidity",4
9,-Oqk1NeaUaPz_f9OSjNd,173.0182,2026-04-21,74.5,36.666660,CRITICAL,33.8125,18:05:07,2026-04-21 18:05:07,1,1,0,0,"temperature,humidity",4
10,-Oqk1RCsp7OVE5a5PCR7,173.0182,2026-04-21,74.5,36.666660,CRITICAL,33.5625,18:05:21,2026-04-21 18:05:21,1,1,0,0,"temperature,humidity",4
11,-Oqk1ju3NNkpFCh4zH73,166.8867,2026-04-21,74.5,36.666660,CRITICAL,32.1875,18:06:40,2026-04-21 18:06:40,1,1,0,0,"temperature,humidity",4
12,-Oqk1nJ2BeeYEsl1wRAf,171.2516,2026-04-21,74.6,36.666660,CRITICAL,32.0000,18:06:56,2026-04-21 18:06:56,1,1,0,0,"temperature,humidity",4
13,-Oqk1qmV9laPuE0GjJpH,165.1614,2026-04-21,74.7,36.666660,CRITICAL,31.8125,18:07:10,2026-04-21 18:07:10,1,1,0,0,"temperature,humidity",4
14,-Oqk296Zd-a7_OEfL-Ga,167.7538,2026-04-21,74.9,36.666660,CRITICAL,31.5000,18:08:29,2026-04-21 18:08:29,1,1,0,0,"temperature,humidity",4
15,-Oqk2Cb1mGjE_TZFngqf,171.2516,2026-04-21,74.9,36.666660,CRITICAL,31.4375,18:08:43,2026-04-21 18:08:43,1,1,0,0,"temperature,humidity",4
16,-Oqk2G9SnQtHKSFoS9pg,171.2516,2026-04-21,74.7,36.666660,CRITICAL,31.4375,18:08:58,2026-04-21 18:08:58,1,1,0,0,"temperature,humidity",4
17,-Oqk2Jka_n009XL1q56g,173.0182,2026-04-21,74.7,36.666660,CRITICAL,31.4375,18:09:12,2026-04-21 18:09:12,1,1,0,0,"temperature,humidity",4
18,-Oqk2NIq7HwhISp-eKRf,173.0182,2026-04-21,75.0,36.666660,CRITICAL,31.3750,18:09:27,2026-04-21 18:09:27,1,1,0,0,"temperature,humidity",4
19,-Oqk2QrqNx0XvJcAabkA,165.1614,2026-04-21,74.8,36.666660,CRITICAL,31.3125,18:09:42,2026-04-21 18:09:42,1,1,0,0,"temperature,humidity",4
20,-Oqk2ULxGqvOvwcVkfq5,173.0182,2026-04-21,75.0,36.666660,CRITICAL,31.3125,18:09:56,2026-04-21 18:09:56,1,1,0,0,"temperature,humidity",4
21,-Oqk2XrxCS2HCq3uRsIc,169.4968,2026-04-21,74.9,36.666660,CRITICAL,31.2500,18:10:10,2026-04-21 18:10:10,1,1,0,0,"temperature,humidity",4
22,-Oqk2aYt24aFUEqw0wFo,173.9059,2026-04-21,74.9,1.666667,CRITICAL,31.3125,18:10:25,2026-04-21 18:10:25,1,1,0,0,"temperature,humidity",4
23,-Oqk2eCLlvkBEfMOnF8A,169.4968,2026-04-21,74.8,36.666660,CRITICAL,31.3125,18:10:40,2026-04-21 18:10:40,1,1,0,0,"temperature,humidity",4
24,-Oqk2hYsy8MEPXgdMF_5,167.7538,2026-04-21,74.9,36.666660,CRITICAL,31.3125,18:10:54,2026-04-21 18:10:54,1,1,0,0,"temperature,humidity",4
25,-Oqk2l6HITwZ8r-7C-X6,166.0226,2026-04-21,74.9,36.666660,CRITICAL,31.3125,18:11:08,2026-04-21 18:11:08,1,1,0,0,"temperature,humidity",4
26,-Oqk2ocCxOUY1nCVB3XR,175.6903,2026-04-21,74.8,36.666660,CRITICAL,31.3125,18:11:23,2026-04-21 18:11:23,1,1,0,0,"temperature,humidity",4
27,-Oqk2s3JY0aNwUdDUpNF,163.4477,2026-04-21,74.8,36.666660,CRITICAL,31.3125,18:11:37,2026-04-21 18:11:37,1,1,0,0,"temperature,humidity",4
28,-Oqk2vSQnXFLbhFOQ8hJ,177.4867,2026-04-21,74.7,36.666660,CRITICAL,31.3125,18:11:51,2026-04-21 18:11:51,1,1,0,0,"temperature,humidity",4
29,-Oqk2yvIdaoVFSLgPZvD,176.5871,2026-04-21,74.8,36.666660,CRITICAL,31.3125,18:12:05,2026-04-21 18:12:05,1,1,0,0,"temperature,humidity",4
30,-Oqk31TXU8qye2p07leb,167.7538,2026-04-21,74.8,36.666660,CRITICAL,31.3125,18:12:20,2026-04-21 18:12:20,1,1,0,0,"temperature,humidity",4
31,-Oqk356M0ccBdWKwNTSZ,169.4968,2026-04-21,74.6,36.666660,CRITICAL,31.3125,18:12:34,2026-04-21 18:12:34,1,1,0,0,"temperature,humidity",4
32,-Oqk38b4YyBJ8ozUGHyI,173.9059,2026-04-21,74.7,36.666660,CRITICAL,31.3125,18:12:49,2026-04-21 18:12:49,1,1,0,0,"temperature,humidity",4
33,-Oqk3C3Qj2lqjhI1h_2X,171.2516,2026-04-21,74.8,36.666660,CRITICAL,31.2500,18:13:03,2026-04-21 18:13:03,1,1,0,0,"temperature,humidity",4
34,-Oqk3FehP1fD1TAGCO2D,173.9059,2026-04-21,74.8,35.833330,CRITICAL,31.3125,18:13:18,2026-04-21 18:13:18,1,1,0,0,"temperature,humidity",4
35,-Oqk3JPF4dg4A8d9jjZn,166.0226,2026-04-21,74.8,35.833330,CRITICAL,31.2500,18:13:33,2026-04-21 18:13:33,1,1,0,0,"temperature,humidity",4
36,-Oqk3MhIXY3NqY99gG_H,169.4968,2026-04-21,75.2,35.833330,CRITICAL,31.2500,18:13:47,2026-04-21 18:13:47,1,1,0,0,"temperature,humidity",4
37,-Oqk3Q02DVNznmHFveFs,157.5416,2026-04-21,75.4,36.666660,CRITICAL,31.2500,18:14:00,2026-04-21 18:14:00,1,1,0,0,"temperature,humidity",4
38,-Oqk3TWK7YJDaVHIs6f1,170.3727,2026-04-21,75.4,36.666660,CRITICAL,31.2500,18:14:15,2026-04-21 18:14:15,1,1,0,0,"temperature,humidity",4
39,-Oqk3X2p477E9Byx_aFl,173.9059,2026-04-21,75.2,36.666660,CRITICAL,31.2500,18:14:29,2026-04-21 18:14:29,1,1,0,0,"temperature,humidity",4